### ISSUE TITLE
exo2nek fails to compile

### ISSUE THREAD

**Issue by aprilnovak** [Nek5000/Nek5000#696] opened 2020-12-17 15:36 UTC
If you do a fresh clone of nekRS/Nek5000 and try to build the tools that ship with Nek5000, the `exo2nek` tool does not build properly. I've attached a build log showing the error for me.

There current workaround for nekRS/Nek5000 users who want to use `exo2nek`:

Use the v19 tarball of nek5000, which points to a repo state before the introduction of the problem in `exo2nek`

[build.log](https://github.com/Nek5000/Nek5000/files/5710460/build.log)

**Comment by stgeke** [comment] 2020-12-17 15:38
This issue in unrelated to nekRS!

**Comment by stgeke** [comment] 2020-12-17 15:41
/home/travis/build/Nek5000/Nek5000/tools/exo2nek/3rd_party/seacas-exodus/packages/seacas/libraries/exodus/include/exodusII.h:27:2: error: #error "Undefined"
 #error "Undefined"

**Comment by aprilnovak** [comment] 2020-12-17 15:41
Nope nevermind, scratch my previous comment - this is specific to exo2nek, not nekRS.

**Comment by stgeke** [comment] 2020-12-17 15:44
You seem to compile exo2nek with an old (cached) 3rd-party dep.

**Comment by aprilnovak** [comment] 2020-12-17 15:45
Yeah, that was the problem. I see the error now with a fresh clone. Sorry for confusion!

**Comment by emerzari** [comment] 2020-12-17 15:46
With the latest?

On Dec 17, 2020, at 10:42 AM, April Novak <notifications@github.com> wrote:

﻿

I think it is specific to nekRS - I can build exo2nek fine in Nek5000:

(standalone)[09:40:44][~/Nek5000/tools]> ./maketools exo2nek
building exo2nek ... done

**Comment by yslan** [comment] 2020-12-17 16:30
This issue is caused by not using a fixed version of EXODUS.
The issue is resolved by upgrading NETCDF to version c-4.7.4

**Closed as completed** 2020-12-19 10:24 UTC
