### ISSUE TITLE
Problem using genmap with large numbers of elements

### ISSUE THREAD

**Issue by rvinuesa** [Nek5000/Nek5000#185] opened 2016-12-22 11:48 UTC
Dear Nek Users,
We are about to set up a new case with about 29692 in 2D, which we would like to extrude to about 150 elements in 3D, giving a total of about 30k times 150 = 4.5M elements. n2to3 works fine, but genmap gives a "periodic mismatch error". Having a lower number of extrusion elements, say 30k times 70 = 2.1M elements, works fine. Changing the tolerance in genmap does not fix it.

Before diving into the code of n2to3 and genmap, we wanted to ask whether somebody has experienced that before, and whether you'd know a potential fix for the problem.

We used both an older version of genmap and the latest github version.

Thanks a lot!
Ricardo

**Comment by pschlatt1** [comment] 2016-12-22 13:55
This seems to be a duplicate of #125. So I guess we can close this.

**Closed as completed** 2016-12-22 13:56 UTC
