### ISSUE TITLE
Issue with 'elmap' corruption in field files of a simulation

### ISSUE THREAD

**Issue by akhoubani** [Nek5000/Nek5000#815] opened 2023-07-31 10:02 UTC
I am experiencing an issue with the `elmap` for some field files from the same simulation. The corruption occurs inconsistently, which leads to discrepancies in the results.

To illustrate the problem, below is an example showing the correct `elmap` of a fine field file and the corresponding corrupted `elmap` from another file of the same simulation.

Correct `elmap`: 
```
[601, 602, 603, 604, 633, 634, 635, 636, 637, 665, 666, 667, 668, 670, 697, 698, 699, 700, 701, 702, 703, 704, 729, 730, 731, 732, 733, 734, 735, 736, 761, 762, 763, 764, 765, 766, 767, 768, 409, 410, 411, 412, 441, 442, 443, 444, 473, 474, 475, 476, 505, 506, 507, 508, 537, 538, 539, 540, 541, 542, 569, 570, 571, 572, 573, 574, 605, 606, 607, 608, 638, 639, 640, 669, 671, 672, 413, 414, 415, 416, 445, 446, 447, 448, 477, 478, 479, 480, 509, 510, 511, 512, 543, 544, 575, 576, 593, 594, 625, 626, 657, 658, 689, 690, 691, 692, 721, 722, 723, 724, 753, 754, 755, 756, 497, 498, 529, 530, 561, 562, 563, 564, 595, 596, 597, 598, 599, 600, 627, 628, 629, 630, 631, 632, 659, 660, 661, 662, 663, 664, 693, 694, 695, 696, 725, 726, 727, 728, 757, 758, 759, 760, 401, 402, 403, 404, 405, 406, 433, 434, 435, 436, 437, 438, 439, 440, 465, 466, 467, 468, 469, 470, 471, 472, 499, 500, 501, 502, 503, 504, 531, 532, 533, 534, 535, 536, 565, 566, 567, 568, 217, 218, 219, 220, 249, 250, 251, 252, 281, 282, 283, 284, 313, 314, 315, 316, 317, 318, 319, 320, 345, 346, 347, 348, 349, 350, 351, 352, 377, 378, 379, 380, 381, 382, 383, 384, 407, 408, 25, 26, 27, 28, 57, 58, 59, 60, 89, 90, 91, 92, 121, 122, 123, 124, 153, 154, 155, 156, 185, 186, 187, 188, 189, 190, 221, 222, 223, 224, 253, 254, 255, 256, 285, 286, 287, 288, 29, 30, 31, 32, 61, 62, 63, 64, 93, 94, 95, 96, 125, 126, 127, 128, 157, 158, 159, 160, 191, 192, 241, 242, 273, 274, 305, 306, 307, 308, 337, 338, 339, 340, 369, 370, 371, 372, 113, 114, 145, 146, 177, 178, 209, 210, 211, 212, 213, 214, 215, 216, 243, 244, 245, 246, 247, 248, 275, 276, 277, 278, 279, 280, 309, 310, 311, 312, 341, 342, 343, 344, 373, 374, 375, 376, 17, 18, 19, 20, 21, 22, 49, 50, 51, 52, 53, 54, 55, 81, 82, 83, 84, 85, 86, 88, 115, 116, 117, 118, 119, 120, 147, 148, 149, 150, 151, 152, 179, 180, 181, 182, 183, 184, 23, 24, 56, 87, 585, 586, 587, 588, 617, 618, 619, 620, 649, 650, 651, 652, 681, 682, 683, 684, 685, 686, 713, 714, 715, 716, 717, 718, 719, 720, 745, 746, 747, 748, 749, 750, 751, 752, 393, 394, 395, 396, 425, 426, 427, 428, 457, 458, 459, 460, 489, 490, 491, 492, 521, 522, 523, 524, 553, 554, 555, 556, 589, 590, 591, 592, 621, 622, 623, 624, 653, 654, 655, 656, 687, 688, 397, 398, 399, 400, 429, 430, 431, 432, 461, 462, 463, 464, 493, 494, 495, 496, 525, 526, 527, 528, 557, 558, 559, 560, 609, 641, 642, 673, 674, 675, 676, 705, 706, 707, 708, 737, 738, 739, 740, 481, 482, 513, 514, 545, 546, 577, 578, 579, 580, 581, 582, 583, 584, 610, 611, 612, 613, 614, 615, 616, 643, 644, 645, 646, 647, 648, 677, 678, 679, 680, 709, 710, 711, 712, 741, 742, 743, 744, 385, 386, 387, 388, 389, 390, 417, 418, 419, 420, 421, 422, 423, 449, 450, 451, 452, 453, 454, 455, 456, 483, 484, 485, 486, 487, 488, 515, 516, 517, 518, 519, 520, 547, 548, 549, 550, 551, 552, 201, 202, 203, 204, 233, 234, 235, 236, 265, 266, 267, 268, 297, 298, 299, 300, 301, 302, 303, 304, 329, 330, 331, 332, 333, 334, 335, 336, 361, 362, 363, 364, 365, 366, 367, 368, 391, 392, 424, 9, 10, 11, 12, 41, 42, 43, 44, 73, 74, 75, 76, 105, 106, 107, 108, 137, 138, 139, 140, 141, 169, 170, 171, 172, 173, 174, 205, 206, 207, 208, 237, 238, 239, 240, 269, 270, 271, 272, 13, 14, 15, 16, 45, 46, 47, 48, 77, 78, 79, 80, 109, 110, 111, 112, 142, 143, 144, 175, 176, 193, 194, 225, 226, 257, 258, 289, 290, 291, 292, 321, 322, 323, 324, 353, 354, 355, 356, 97, 98, 129, 130, 131, 161, 162, 163, 164, 195, 196, 197, 198, 199, 200, 227, 228, 229, 230, 231, 232, 259, 260, 261, 262, 263, 264, 293, 294, 295, 296, 325, 326, 327, 328, 357, 358, 359, 360, 1, 2, 3, 4, 5, 6, 7, 8, 33, 34, 35, 36, 37, 38, 39, 40, 65, 66, 67, 68, 69, 70, 71, 72, 99, 100, 101, 102, 103, 104, 132, 133, 134, 135, 136, 165, 166, 167, 168]
```

Corrupted `elmap`: 
```
[601, 602, 603, 604, 633, 634, 635, 636, 637, 665, 666, 667, 668, 670, 697, 698, 699, 700, 701, 702, 703, 704, 729, 730, 731, 732, 733, 734, 735, 736, 761, 762, 763, 764, 765, 766, 767, 768, 409, 410, 411, 412, 441, 442, 443, 444, 473, 474, 475, 476, 505, 506, 507, 508, 537, 538, 539, 540, 541, 542, 569, 570, 571, 572, 573, 574, 605, 606, 607, 608, 638, 639, 640, 669, 671, 672, 413, 414, 415, 416, 445, 446, 447, 448, 477, 478, 479, 480, 509, 510, 511, 512, 543, 544, 575, 576, 593, 594, 625, 626, 657, 658, 689, 690, 691, 692, 721, 722, 723, 724, 753, 754, 755, 756, 497, 498, 529, 530, 561, 562, 563, 564, 595, 596, 597, 598, 599, 600, 627, 628, 629, 630, 631, 632, 659, 660, 661, 662, 663, 664, 693, 694, 695, 696, 725, 726, 727, 728, 757, 758, 759, 760, 401, 402, 403, 404, 405, 406, 433, 434, 435, 436, 437, 438, 439, 440, 465, 466, 467, 468, 469, 470, 471, 472, 499, 500, 501, 502, 503, 504, 531, 532, 533, 534, 535, 536, 565, 566, 567, 568, 217, 218, 219, 220, 249, 250, 251, 252, 281, 282, 283, 284, 313, 314, 315, 316, 317, 318, 319, 320, 345, 346, 347, 348, 349, 350, 351, 352, 377, 378, 379, 380, 381, 382, 383, 384, 407, 408, 25, 26, 27, 28, 57, 58, 59, 60, 89, 90, 91, 92, 121, 122, 123, 124, 153, 154, 155, 156, 185, 186, 187, 188, 189, 190, 221, 222, 223, 224, 253, 254, 255, 256, 285, 286, 287, 288, 29, 30, 31, 32, 61, 62, 63, 64, 93, 94, 95, 96, 125, 126, 127, 128, 157, 158, 159, 160, 191, 192, 241, 242, 273, 274, 305, 306, 307, 308, 337, 338, 339, 340, 369, 370, 371, 372, 113, 114, 145, 146, 177, 178, 209, 210, 211, 212, 213, 214, 215, 216, 243, 244, 245, 246, 247, 248, 275, 276, 277, 278, 279, 280, 309, 310, 311, 312, 341, 342, 343, 344, 373, 374, 375, 376, 17, 18, 19, 20, 21, 22, 49, 50, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2577, 0, 1870113760, 32563, 1870113760, 32563, 0, 0, 0, 0, 65536, 1, 0, 0, 176, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 7, 8, 33, 34, 35, 36, 37, 38, 39, 40, 65, 66, 67, 68, 69, 70, 71, 72, 99, 100, 101, 102, 103, 104, 132, 133, 134, 135, 136, 165, 166, 167, 168]
```

I am unable to identify the source of this discrepancy. I would greatly appreciate any advice or potential solutions to fix this issue.

**Comment by stgeke** [comment] 2023-08-01 10:09
I cannot reproduce this on my end. Do you have a small reproducer?

**Comment by stgeke** [comment] 2023-08-26 06:43
I will close this for now. If you think there is still an issue feel free to reopen it.

**Closed as completed by stgeke** 2023-08-26 06:43 UTC
