### ISSUE TITLE
exo2nek tool

### ISSUE THREAD

**Issue by jklai12** [Nek5000/Nek5000#230] opened 2017-03-13 22:04 UTC
I tried to get exo2nek to compile and couldn't get it to work with a 64-bit system. I noticed that the README says to use the "exoIIv2for32" libraries, but even after trying the other libraries from seacas-exodus, I was getting errors.

I had to use a 32-bit machine to convert the exodus file to re2 / rea, and am attaching a quick documentation of what I did.
[exo2nek_info.pdf](https://github.com/Nek5000/Nek5000/files/839733/exo2nek_info.pdf)

In the future, could we find a way to make this tool work smoothly for 64-bit systems?

**Comment by ggiannako** [comment] 2017-03-14 11:47
The tool works fine in 64-bit systems. The "Relocation truncated to fit" error you report is memory-related and specific to your system. You may consider reducing the maximum number of elements in exo2nek/SIZE file and/or use the BIGMEM="TRUE" flag in maketools when compiling.

In general, you do not need to modify exo2nek.f and recompile in order to specify your case-specific BCs. The exodus sideset IDs are passed into the 5th argument of the velocity BC array. 
You can relate a sideset to a Nek BC later on in the .usr file, for example by doing something along the following lines (say, in usrdat2):
 
```
do iel=1,nelv
   do ifc=1,2*ndim
      id_face = bc(5,ifc,iel,1)
      if (id_face.eq.1) then       ! SideSet 1
         cbc(ifc,iel,1) = 'v  '
      elseif (id_face.eq.2) then   ! SideSet 2
         cbc(ifc,iel,1) = 'O  '
      elseif (id_face.eq.3) then   ! SideSet 3
         cbc(ifc,iel,1) = 'W  '
      endif
   enddo
enddo 
```

**Comment by stgeke** [comment] 2017-03-14 15:09
I am closing this issue because it's not a bug. We may want to use dynamic memory allocation in a future version.

**Closed as completed by stgeke** 2017-03-14 15:09 UTC
